name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: find /github/workspace
      
#     - name: One Click Docker
#       uses: pangzineng/Github-Action-One-Click-Docker@v1.1.1
#       env: 
#         DOCKER_USERNAME: teamatlas
#         DOCKER_NAMESPACE: teamatlas
